# Generated by fixnix on 2020-04-30
# $ fixnix --repo=ucla-pls/javaq --branch=master --no-import
builtins.fetchTarball {
  name   = "javaq_master_2e8764";
  url    = "https://github.com/ucla-pls/javaq/archive/2e8764ef8432cf526252bb8b020456b70540d267.tar.gz";
  sha256 = "031swrnnn29scv6lxb4z1c1bhjg2nlq6d4p9n4hircf0p331ialr";
}
