# Generated by fixnix on 2020-04-29
# $ fixnix --repo=ucla-pls/javaq --branch=master --no-import
builtins.fetchTarball {
  name   = "javaq_master_4c5e45";
  url    = "https://github.com/ucla-pls/javaq/archive/4c5e451588d85436fbd42a1fbdcc459ddbadf2bb.tar.gz";
  sha256 = "1jr5r96i09jc15s8lg2gz9fdv4rf11h51lk4zjdbznpbc8a299wy";
}
