# Generated by fixnix on 2020-04-29
# $ fixnix --repo=ucla-pls/jreduce --branch=logic --no-import
builtins.fetchTarball {
  name   = "jreduce_logic_6c324f";
  url    = "https://github.com/ucla-pls/jreduce/archive/6c324fffbd7b6fbad3b022c16b127b3baa95b69a.tar.gz";
  sha256 = "0m8rgp9zx5hchwya0x5ih3mjqihdmsawyhfiddxrkz20w8n4jj4a";
}
