# Generated by fixnix on 2020-05-02
# $ fixnix --repo=kalhauge/nixec --branch=master
import (builtins.fetchTarball {
  name   = "nixec_master_2fa4d3";
  url    = "https://github.com/kalhauge/nixec/archive/2fa4d3be9626fdbd63e87cb23b43c59a1106f66d.tar.gz";
  sha256 = "1f7m6fdyizydanavhhv1gn17r2aidj4fq8n4y71hpin6f9zc2xxd";
})
